In [1]:
%load_ext autoreload
%autoreload 2
import tensorflow as tf

tf.config.list_physical_devices()

c:\ProgramData\Anaconda3\envs\thesis\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.12.2 when it was built against 1.12.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
import numpy as np
from loader.CSVLoader import csv_loader

gt,wave = csv_loader()

name="cr_sg_dwt"

all_data = np.load(f"./experiment5/{name}.npy")
test_data = np.load(f'./experiment5/{name}_test.npy')


all_data.shape

(1732, 300)

In [3]:
from creators.CNN3DCreator import  CNN3DNetworkParams
from creators.CRNNCreator import CRNNNetworkParams
from creators.ModelParams import ConvolutionalRecurrentLayerParams, Conv1DParams, Conv2DParams, Conv3DParams, DeepLayerParams, FlattenParams, GenericNeuralNetworkParams, RandomForestParams, RecurrentLayerParams, SVRParams
from creators.CNN1DCreator import  CNN1DNetworkParams
from creators.CNN2DCreator import  CNN2DNetworkParams
from creators.CLSTMCreator import CLSTMNetworkParams
from prep.HelperBlocks import pipe, split_3d_to_timeseries
import tensorflow as tf
from prep.MSCBlock import msc_block, msc_block1d

from prep.Normlize import normalize_layers

drop=0.53
epochs=150
optimizer = tf.keras.optimizers.Adam
folds = 5
params_rf = RandomForestParams(lambda data, is_test: normalize_layers(data,not is_test))

In [5]:
from ModelExperiment import ModelExperiment

experiment = ModelExperiment()
experiment.run_experiment(
    params_vector=[params_rf],
    data=[all_data],
    gt=[gt["pH"].values],
    folds=folds,
    test_data=[test_data]
)

c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountered in divide
  input_data = (
c:\Users\Wiktor\Desktop\Praca Magisterska\Thesis Code\src\prep\Normlize.py:9: RuntimeWarning: invalid value encountere

In [25]:

experiment.models[0].save_history('./experiment5/test2_K.csv')
experiment.models[1].save_history('./experiment5/test2_P.csv')
experiment.models[2].save_history('./experiment5/test2_Mg.csv')

In [26]:
experiment.get_errors_report('./experiment5/test_2.csv')

In [10]:
print(experiment.models[0].crossval_scores)
print(experiment.models[0].crossval_rs)
print(experiment.models[0].mae)

experiment.models[0].crossval_scores.mean()

[0.83413439 0.81692079 0.80476689 0.80205568 0.8377336 ]
[0.16584181 0.18138464 0.19522559 0.19581103 0.16226544]
[0.18193718 0.18102398 0.17812185 0.17198867 0.18366844]


0.8191222688814566

In [9]:
res=  np.array(experiment.models[0].predicted_test_values)
np.save("./predict/pH",res)

In [ ]:
print(experiment.models[5].crossval_scores)
print(experiment.models[5].crossval_rs)
print(experiment.models[5].mae)

[0.92924521 0.93309339 0.90434612 0.91175416 0.97988553]
[0.07072827 0.06497107 0.09564543 0.08582077 0.02011335]
[0.19262939 0.19733602 0.19221746 0.18549364 0.19679249]
